matrix:
  include:
    - os: linux
    - os: osx

dist: trusty

before_install:
  - ci/travis-before-install.sh
  - export bB=`pwd`
  - export PATH=$PATH:$bB

script:
  - ci/travis-build.sh sample.bas

notifications:
  email: false